// <auto-generated />
using CheckoutApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CheckoutApp.DataAccess.Migrations
{
    [DbContext(typeof(BasketContext))]
    partial class BasketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CheckoutApp.Domain.Models.ArticleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Item")
                        .IsRequired();

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.HasIndex("Item")
                        .IsUnique();

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Item = "Book",
                            Price = 20.0
                        },
                        new
                        {
                            Id = 2,
                            Item = "Pencil",
                            Price = 30.0
                        },
                        new
                        {
                            Id = 3,
                            Item = "Paper",
                            Price = 12.0
                        });
                });

            modelBuilder.Entity("CheckoutApp.Domain.Models.BasketArticleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BasketId");

                    b.Property<int>("ItemId");

                    b.HasKey("Id");

                    b.ToTable("BasketArticles");
                });

            modelBuilder.Entity("CheckoutApp.Domain.Models.BasketDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Close");

                    b.Property<string>("Customer")
                        .IsRequired();

                    b.Property<bool>("Payed");

                    b.Property<bool>("PaysVAT");

                    b.Property<double>("TotalGross");

                    b.Property<double>("TotalNet");

                    b.HasKey("Id");

                    b.ToTable("Baskets");
                });
#pragma warning restore 612, 618
        }
    }
}
